// This file is generated by GoAdmin CLI adm.
package main

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "courses" => http://localhost:9033/admin/info/courses
// "teachers" => http://localhost:9033/admin/info/teachers
//
// example end
var Generators = map[string]table.Generator{

	//"courses":  GetCoursesTable,
	//"teachers": GetTeachersTable,

	// generators end
}
